shallow_clone: true # download the zip instead of the whole history

environment:

    global:
        PACKAGES:
            - "numpy=1.10"
        # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
        # /E:ON and /V:ON options are not enabled in the batch script intepreter
        # See: http://stackoverflow.com/a/13751649/163740
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci\\appveyor\\windows_sdk.cmd"
        TEST_CMD: "python -c 'import numpy as np;print(np.version.version)'"

    matrix:
        - PYTHON_VERSION: "2.7"
          PYTHON_ARCH: "32"
          platform: x86
          PYTHON: "C:\\Python27_32"

        - PYTHON_VERSION: "2.7"
          PYTHON_ARCH: "64"
          platform: x64
          PYTHON: "C:\\Python27_64"

        - PYTHON_VERSION: "3.4"
          PYTHON_ARCH: "32"
          platform: x86
          PYTHON: "C:\\Python34_32"

        - PYTHON_VERSION: "3.4"
          PYTHON_ARCH: "64"
          platform: x64
          PYTHON: "C:\\Python34_64"

install:
    # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit)
    - python -u ci\appveyor\conda_setup.py
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: false

test_script:
    - "%CMD_IN_ENV% %TEST_CMD%"
